# Generated by Django 4.2 on 2024-11-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_county_name_af_county_name_ar_county_name_ar_dz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='min_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
