# Generated by Django 4.2 on 2024-11-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_county_name_af_remove_county_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='room'),
        ),
    ]
