# Generated by Django 4.2 on 2024-11-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_house_room_en_house_room_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='county',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name_ru',
        ),
        migrations.AlterField(
            model_name='user',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.county'),
        ),
        migrations.AlterField(
            model_name='user',
            name='county_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.county'),
        ),
        migrations.AlterField(
            model_name='user',
            name='county_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.county'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.state'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.state'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.state'),
        ),
    ]
