# Generated by Django 4.2 on 2024-11-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_county_name_en_remove_county_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='county_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='county_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state_ru',
        ),
        migrations.AddField(
            model_name='county',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='county',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='state',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='state',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
    ]
