# Generated by Django 4.2 on 2024-11-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_remove_user_county_en_remove_user_county_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='room_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='room_ru',
        ),
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
