# Generated by Django 4.2 on 2024-11-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_remove_user_room_en_remove_user_room_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='room'),
        ),
        migrations.AddField(
            model_name='user',
            name='room_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='room'),
        ),
    ]
