# Generated by Django 4.2 on 2024-11-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_houseimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHouseSelection',
        ),
    ]
