# Generated by Django 4.2 on 2024-11-13 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_delete_userhouseselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_room_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedroom_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bathroom_count', models.PositiveIntegerField()),
                ('kitchen_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year_built', models.PositiveIntegerField()),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='bot.house')),
            ],
        ),
    ]
