# Generated by Django 4.2 on 2024-11-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_housemeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemeasure',
            name='bathroom_count',
            field=models.PositiveIntegerField(verbose_name='Hojatxonalar soni'),
        ),
        migrations.AlterField(
            model_name='housemeasure',
            name='bedroom_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yotoq xona maydoni (kvadrat metr)'),
        ),
        migrations.AlterField(
            model_name='housemeasure',
            name='kitchen_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Oshxona maydoni'),
        ),
        migrations.AlterField(
            model_name='housemeasure',
            name='living_room_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Oshxona maydoni (kvadrat metr)'),
        ),
        migrations.AlterField(
            model_name='housemeasure',
            name='total_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy maydon (kvadrat metr)'),
        ),
        migrations.AlterField(
            model_name='housemeasure',
            name='year_built',
            field=models.PositiveIntegerField(verbose_name='Qurilish yili'),
        ),
    ]
