# Generated by Django 4.2 on 2024-11-13 08:25

import bot.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_alter_housemeasure_bathroom_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='zipcode',
            field=models.FloatField(blank=True, null=True, validators=[bot.validators.validate_us_zipcode]),
        ),
    ]
